version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15
    container_name: clausonus-postgres
    environment:
      POSTGRES_DB: loja_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha_segura
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - clausonus-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplicação Quarkus
  loja-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clausonus-loja
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/loja_db
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=senha_segura
      - QUARKUS_HTTP_PORT=8080
      - QUARKUS_PROFILE=dev
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - clausonus-network

  # PgAdmin para gerenciamento do banco de dados
  pgadmin:
    image: dpage/pgadmin4:6.21
    container_name: clausonus-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@clausonus.com.br
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - clausonus-network

networks:
  clausonus-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: